### ISSUE TITLE
Some errors of ‘cargo run’

### ISSUE THREAD

**Issue by JialeDeng** [RUB-SysSec/nautilus#10]
Hi! I'm reading the paper recently, which is well written. But when I was running the command "cargo run -p gramophone --release --bin fuzzer", I got the following errors:

error[E0407]: method `replace_one` is not a member of trait `Step`
  --> grammartec/src/newtypes.rs:72:5
   |
72 | /     fn replace_one(&mut self) -> Self {
73 | |         return NodeID::from(0);
74 | |     }
   | |_____^ not a member of trait `Step`

error[E0407]: method `replace_zero` is not a member of trait `Step`
  --> grammartec/src/newtypes.rs:75:5
   |
75 | /     fn replace_zero(&mut self) -> Self {
76 | |         return NodeID::from(1);
77 | |     }
   | |_____^ not a member of trait `Step`

error[E0407]: method `add_one` is not a member of trait `Step`
  --> grammartec/src/newtypes.rs:78:5
   |
78 | /     fn add_one(&self) -> Self {
79 | |         return self.add(1);
80 | |     }
   | |_____^ not a member of trait `Step`

error[E0407]: method `sub_one` is not a member of trait `Step`
  --> grammartec/src/newtypes.rs:81:5
   |
81 | /     fn sub_one(&self) -> Self {
82 | |         return NodeID(self.0 - 1);
83 | |     }
   | |_____^ not a member of trait `Step`

error[E0407]: method `add_usize` is not a member of trait `Step`
  --> grammartec/src/newtypes.rs:84:5
   |
84 | /     fn add_usize(&self, n: usize) -> Option<Self> {
85 | |         match self.0.checked_add(n) {
86 | |             Some(x) => return Some(NodeID::from(x)),
87 | |             None => return None,
88 | |         }
89 | |     }
   | |_____^ not a member of trait `Step`

I think it may be a problem with the version of rust I use. Which version do you use? Thanks a lot.

**Comment by eqv** [comment]
That's most certainly a problem with your rust version (I remember seeing the same error earlier). You probably want to use the current release found here: https://github.com/nautilus-fuzz/nautilus. It also contains a rust-toolchain file that specifies a working rustc version https://github.com/nautilus-fuzz/nautilus/blob/master/rust-toolchain. If you want to use the old version to reproduce our experiments, you can try the same version.
