### ISSUE TITLE
example command

### ISSUE THREAD

**Issue by wideglide** [RUB-SysSec/nautilus#2]
this command seems to not be correct for this repository?

`python scripts/local_snapshotter.py outputs $HOME/tmp/gfsnapshots cargo -p gramophone run --release --bin fuzzer -- forksrv/instrument/mruby/bin/mruby antlr_parser/src/ruby_new_antlr_grammar.json`

`local_snaphotter.py` exists in the gramophone directory, but references `timer.sh` in the local directory.

fixing the directory references, `fuzzer` still produces an error:
- error: Found argument 'antlr_parser/src/ruby_new_antlr_grammar.json' which wasn't expected, or isn't valid in this context

**Comment by eqv** [comment]
fixed
