### ISSUE TITLE
Building of PHP-7.2.6 fails with Redqueen toolchain

### ISSUE THREAD

**Issue by prashast** [RUB-SysSec/nautilus#5]
Hi, I was trying to fuzz PHP-7.2.6 with Nautilus as this was the version tagged in the paper but while trying to build the fuzz target with `redqueen` as was done for the mruby target (providing the same CC, CXX, and LD), it would fail with the following error:
```make
/root/php-src/main/reentrancy.c:139:2: warning: 'readdir_r' is deprecated
      [-Wdeprecated-declarations]
        readdir_r(dirp, entry);
        ^
/usr/include/dirent.h:183:12: note: 'readdir_r' has been explicitly marked
      deprecated here
extern int readdir_r (DIR *__restrict __dirp,
           ^
/root/php-src/main/reentrancy.c:139:23: error: too few arguments to function call,
      expected 3, have 2
        readdir_r(dirp, entry);
        ~~~~~~~~~            ^
/usr/include/dirent.h:183:1: note: 'readdir_r' declared here
extern int readdir_r (DIR *__restrict __dirp,
^
1 warning and 1 error generated.
```
Is there some specific patch that I can apply to make it work. Also, I assume Nautilus has a Redqueen dependency? I tried running it on the PHP target compiled with just vanilla GCC and the fuzzer panicked and quit.

**Comment by RUB-SysSec** [comment]
have you tried compiling php-7.2.6 with clang? Our "custom" compiler is just a script that ends up calling clang, and it seems like this might be a clang issue... 

btw if you want to report the bugs that you find, don't bother with PHP, they gave up on building a secure interpreter - they can't even be bothered to fix the bugs that we reported, much less acknowledge them.

**Comment by prashast** [comment]
Thanks for the feedback. I'd pivoted to other things and didn't get time to address this. Yes, `clang-3.8` turned out to be the reason for the PHP miscompilation. Bumping everything up to `clang-4.0` for Nautilus solved the issue of running it on PHP. 

This can be done by following these steps:
- Applying this patch first onto the repo:https://gist.github.com/prashast/3092f527dd71aaf77a6311b4d03dcf30 ( Make sure to fix up absolute paths in `config.ron` appropriately)

- Recompiling Nautilus' `clang_wrapper` ( https://github.com/RUB-SysSec/nautilus/tree/master/forksrv/instrument/clang_wrapper) 

- Compiling PHP with the following configuration (again fix up paths):
```
ASAN_OPTIONS=detect_leaks=0 CC=/root/nautilus/forksrv/instrument/clang_wrapper/redqueen-clang CXX=/root/nautilus/forksrv/instrument/clang_wrapper/redqueen-clang++ LD=/root/nautilus/forksrv/instrument/clang_wrapper/redqueen-clang ./configure
``` 
This should allow folks to fuzz the latest version of PHP with Nautilus. Also, thanks for the heads up regarding PHP's attitude to bugs, will keep that in mind. :)
